# Configuración de EUREKA
title: "EUREKA"
author: "Prof. Ing. Luciano Lamaita"
logo: _static/logo.png  # Asegúrate de poner un logo aquí luego

# Configuración de ejecución (por ahora no ejecutamos celdas de código)
execute:
  execute_notebooks: off

# Configuración de HTML (Diseño)
html:
  theme: sphinx_book_theme
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  home_page_in_toc: true
  extra_navbar: |
    Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  
# Extensiones de Sphinx (Para que se vea como el de la UGR)
sphinx:
  config:
    html_show_copyright: false
    # Habilitamos los recuadros de colores (Admonitions) y diseño de rejilla
    extensions:
      - sphinx_design